name: SAPIEN3 CI Checks on GitHub

on: [push]

jobs:
  integration-tests:
    runs-on: codebuild-Tmp2-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
        - uses: actions/checkout@v4
        - run: docker build -f ci/docker/Dockerfile.lightweight -t ci.lightweight .
        - run: docker run -d --runtime=nvidia --privileged=true -v .:/root/RoboVerse -it --name ci.lightweight ci.lightweight
        - run: >
            docker exec ci.lightweight
            conda run --no-capture-output -n metasim
            python metasim/test/state_consistency.py --sim=sapien3
