name: SAPIEN3 CI Checks on GitHub

on: [push]

jobs:
  integration-tests:
    runs-on: codebuild-RoboVerse-CI-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10.17'
        - run: pip install uv
        - run: uv pip install --system -e ".[sapien3]"
        - run: >
            python metasim/test/state_consistency.py --sim=sapien3
